require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SnapsController do

  # This should return the minimal set of attributes required to create a valid
  # Snap. As you add validations to Snap, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all snaps as @snaps" do
      snap = Snap.create! valid_attributes
      get :index
      assigns(:snaps).should eq([snap])
    end
  end

  describe "GET show" do
    it "assigns the requested snap as @snap" do
      snap = Snap.create! valid_attributes
      get :show, :id => snap.id
      assigns(:snap).should eq(snap)
    end
  end

  describe "GET new" do
    it "assigns a new snap as @snap" do
      get :new
      assigns(:snap).should be_a_new(Snap)
    end
  end

  describe "GET edit" do
    it "assigns the requested snap as @snap" do
      snap = Snap.create! valid_attributes
      get :edit, :id => snap.id
      assigns(:snap).should eq(snap)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Snap" do
        expect {
          post :create, :snap => valid_attributes
        }.to change(Snap, :count).by(1)
      end

      it "assigns a newly created snap as @snap" do
        post :create, :snap => valid_attributes
        assigns(:snap).should be_a(Snap)
        assigns(:snap).should be_persisted
      end

      it "redirects to the created snap" do
        post :create, :snap => valid_attributes
        response.should redirect_to(Snap.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved snap as @snap" do
        # Trigger the behavior that occurs when invalid params are submitted
        Snap.any_instance.stub(:save).and_return(false)
        post :create, :snap => {}
        assigns(:snap).should be_a_new(Snap)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Snap.any_instance.stub(:save).and_return(false)
        post :create, :snap => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested snap" do
        snap = Snap.create! valid_attributes
        # Assuming there are no other snaps in the database, this
        # specifies that the Snap created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Snap.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => snap.id, :snap => {'these' => 'params'}
      end

      it "assigns the requested snap as @snap" do
        snap = Snap.create! valid_attributes
        put :update, :id => snap.id, :snap => valid_attributes
        assigns(:snap).should eq(snap)
      end

      it "redirects to the snap" do
        snap = Snap.create! valid_attributes
        put :update, :id => snap.id, :snap => valid_attributes
        response.should redirect_to(snap)
      end
    end

    describe "with invalid params" do
      it "assigns the snap as @snap" do
        snap = Snap.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Snap.any_instance.stub(:save).and_return(false)
        put :update, :id => snap.id, :snap => {}
        assigns(:snap).should eq(snap)
      end

      it "re-renders the 'edit' template" do
        snap = Snap.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Snap.any_instance.stub(:save).and_return(false)
        put :update, :id => snap.id, :snap => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested snap" do
      snap = Snap.create! valid_attributes
      expect {
        delete :destroy, :id => snap.id
      }.to change(Snap, :count).by(-1)
    end

    it "redirects to the snaps list" do
      snap = Snap.create! valid_attributes
      delete :destroy, :id => snap.id
      response.should redirect_to(snaps_url)
    end
  end

end
